// Mocks generated by Mockito 5.4.4 from annotations
// in mobile_app_notifications/test/prayer_services_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mobile_app_notifications/models/mosque/detailed_mosque.dart'
    as _i2;
import 'package:mobile_app_notifications/models/notification/notification_info_model.dart'
    as _i6;
import 'package:mobile_app_notifications/models/prayers/prayer_notification.dart'
    as _i3;
import 'package:mobile_app_notifications/prayer_services.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDetailedMosque_0 extends _i1.SmartFake
    implements _i2.DetailedMosque {
  _FakeDetailedMosque_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrayerNotification_1 extends _i1.SmartFake
    implements _i3.PrayerNotification {
  _FakePrayerNotification_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DetailedMosque].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailedMosque extends _i1.Mock implements _i2.DetailedMosque {
  MockDetailedMosque() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get iqamaEnabled => (super.noSuchMethod(
        Invocation.getter(#iqamaEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isVirtual => (super.noSuchMethod(
        Invocation.getter(#isVirtual),
        returnValue: false,
      ) as bool);

  @override
  set uuid(String? _uuid) => super.noSuchMethod(
        Invocation.setter(
          #uuid,
          _uuid,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set name(String? _name) => super.noSuchMethod(
        Invocation.setter(
          #name,
          _name,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set label(String? _label) => super.noSuchMethod(
        Invocation.setter(
          #label,
          _label,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set phone(String? _phone) => super.noSuchMethod(
        Invocation.setter(
          #phone,
          _phone,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set email(String? _email) => super.noSuchMethod(
        Invocation.setter(
          #email,
          _email,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set site(String? _site) => super.noSuchMethod(
        Invocation.setter(
          #site,
          _site,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set localisation(String? _localisation) => super.noSuchMethod(
        Invocation.setter(
          #localisation,
          _localisation,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set longitude(double? _longitude) => super.noSuchMethod(
        Invocation.setter(
          #longitude,
          _longitude,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set latitude(double? _latitude) => super.noSuchMethod(
        Invocation.setter(
          #latitude,
          _latitude,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set image(String? _image) => super.noSuchMethod(
        Invocation.setter(
          #image,
          _image,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set url(String? _url) => super.noSuchMethod(
        Invocation.setter(
          #url,
          _url,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set paymentWebsite(String? _paymentWebsite) => super.noSuchMethod(
        Invocation.setter(
          #paymentWebsite,
          _paymentWebsite,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set jumua(String? _jumua) => super.noSuchMethod(
        Invocation.setter(
          #jumua,
          _jumua,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set jumua2(String? _jumua2) => super.noSuchMethod(
        Invocation.setter(
          #jumua2,
          _jumua2,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set womenSpace(bool? _womenSpace) => super.noSuchMethod(
        Invocation.setter(
          #womenSpace,
          _womenSpace,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set janazaPrayer(bool? _janazaPrayer) => super.noSuchMethod(
        Invocation.setter(
          #janazaPrayer,
          _janazaPrayer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set aidPrayer(bool? _aidPrayer) => super.noSuchMethod(
        Invocation.setter(
          #aidPrayer,
          _aidPrayer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set aidPrayerTime(String? _aidPrayerTime) => super.noSuchMethod(
        Invocation.setter(
          #aidPrayerTime,
          _aidPrayerTime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set aidPrayerTime2(String? _aidPrayerTime2) => super.noSuchMethod(
        Invocation.setter(
          #aidPrayerTime2,
          _aidPrayerTime2,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set childrenCourses(bool? _childrenCourses) => super.noSuchMethod(
        Invocation.setter(
          #childrenCourses,
          _childrenCourses,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set adultCourses(bool? _adultCourses) => super.noSuchMethod(
        Invocation.setter(
          #adultCourses,
          _adultCourses,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set ramadanMeal(bool? _ramadanMeal) => super.noSuchMethod(
        Invocation.setter(
          #ramadanMeal,
          _ramadanMeal,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set handicapAccessibility(bool? _handicapAccessibility) => super.noSuchMethod(
        Invocation.setter(
          #handicapAccessibility,
          _handicapAccessibility,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set ablutions(bool? _ablutions) => super.noSuchMethod(
        Invocation.setter(
          #ablutions,
          _ablutions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set parking(bool? _parking) => super.noSuchMethod(
        Invocation.setter(
          #parking,
          _parking,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set jumuaAsDuhr(bool? _jumuaAsDuhr) => super.noSuchMethod(
        Invocation.setter(
          #jumuaAsDuhr,
          _jumuaAsDuhr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastModifiedHeaderTimes(String? _lastModifiedHeaderTimes) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastModifiedHeaderTimes,
          _lastModifiedHeaderTimes,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastModifiedHeaderInfo(String? _lastModifiedHeaderInfo) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastModifiedHeaderInfo,
          _lastModifiedHeaderInfo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastModifiedHeaderHijri(String? _lastModifiedHeaderHijri) =>
      super.noSuchMethod(
        Invocation.setter(
          #lastModifiedHeaderHijri,
          _lastModifiedHeaderHijri,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set countryCode(String? _countryCode) => super.noSuchMethod(
        Invocation.setter(
          #countryCode,
          _countryCode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [PrayerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrayerService extends _i1.Mock implements _i4.PrayerService {
  MockPrayerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get prayerKeys => (super.noSuchMethod(
        Invocation.getter(#prayerKeys),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<List<_i6.NotificationInfoModel>> getPrayers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrayers,
          [],
        ),
        returnValue: _i5.Future<List<_i6.NotificationInfoModel>>.value(
            <_i6.NotificationInfoModel>[]),
      ) as _i5.Future<List<_i6.NotificationInfoModel>>);

  @override
  _i5.Future<_i3.PrayerNotification?> getPrayerDataByIndex(
    _i2.DetailedMosque? mosque,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrayerDataByIndex,
          [
            mosque,
            index,
          ],
        ),
        returnValue: _i5.Future<_i3.PrayerNotification?>.value(),
      ) as _i5.Future<_i3.PrayerNotification?>);

  @override
  DateTime? getPrayerTime(
    _i2.DetailedMosque? mosque,
    String? key, {
    DateTime? time,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getPrayerTime,
        [
          mosque,
          key,
        ],
        {#time: time},
      )) as DateTime?);

  @override
  _i5.Future<_i2.DetailedMosque> getMosque(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #getMosque,
          [uuid],
        ),
        returnValue: _i5.Future<_i2.DetailedMosque>.value(_FakeDetailedMosque_0(
          this,
          Invocation.method(
            #getMosque,
            [uuid],
          ),
        )),
      ) as _i5.Future<_i2.DetailedMosque>);
}

/// A class which mocks [PrayerNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrayerNotificationService extends _i1.Mock
    implements _i3.PrayerNotificationService {
  MockPrayerNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.PrayerNotification> getPrayerNotificationFromDB(
          String? prayerKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrayerNotificationFromDB,
          [prayerKey],
        ),
        returnValue:
            _i5.Future<_i3.PrayerNotification>.value(_FakePrayerNotification_1(
          this,
          Invocation.method(
            #getPrayerNotificationFromDB,
            [prayerKey],
          ),
        )),
      ) as _i5.Future<_i3.PrayerNotification>);
}
